In [85]:
import pandas as pd
from sklearn.decomposition import PCA
import numpy as np

In [86]:
prices = pd.read_csv('close_prices.csv')

In [87]:
prices.head()

date        AXP          BA        CAT       CSCO         CVX  \
0  2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
1  2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2  2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   
3  2013-09-26  76.320000  119.379997  84.199997  23.770000  123.489998   
4  2013-09-27  75.889999  118.739998  83.800003  23.330000  122.639999   

          DD        DIS         GE          GS  ...        PFE         PG  \
0  59.409999  64.750000  24.280001  165.250000  ...  28.799999  79.279999   
1  59.319997  64.320000  24.320000  162.970001  ...  28.709999  78.620003   
2  59.319997  64.449997  24.230000  162.309998  ...  28.490000  77.720001   
3  59.509996  65.239998  24.250000  162.289993  ...  28.520000  78.050003   
4  59.009995  65.190002  24.049999  159.850006  ...  28.879999  77.209999   

           T        TRV        UNH         UTX           V         VZ  \
0  34.220001  86.379997  71.820000  109.419998  196.240005  47.980000   
1  34.090000  85.870003  72.320000  110.000000  193.339996  47.270000   
2  34.049999  85.980003  71.980003  109.260002  191.559998  46.950001   
3  34.230000  85.830002  72.160004  109.660004  193.559998  47.669998   
4  33.980000  85.410004  71.989998  109.360001  193.050003  47.000000   

         WMT        XOM  
0  76.419998  87.750000  
1  75.750000  87.360001  
2  74.650002  87.139999  
3  74.620003  87.070000  
4  74.360001  86.900002  

[5 rows x 31 columns]

In [88]:
companies = prices.columns.values[1:]

In [89]:
def components_count_for_some_sum(nums, limit):
    count = 0
    summ = 0.0
    for num in sorted(nums, reverse=True):
        if summ >= limit:
            return count
        summ += num
        count += 1
    return None    

In [90]:
pca = PCA(n_components=10)

pca.fit(prices.iloc[:, 1:])

PCA(n_components=10)

In [91]:
pca.explained_variance_ratio_

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

In [92]:
result = components_count_for_some_sum(pca.explained_variance_ratio_, 0.9)

In [93]:
with open('1.txt', 'w') as f:
    f.write(str(result))

In [107]:
prices_pca = pca.transform(prices.iloc[:, 1:])
print(prices_pca)
prices_pca = pd.DataFrame(prices_pca)
prices_pca['date'] = prices['date']
prices_pca = prices_pca[['date'] + prices_pca.columns.tolist()[0:-1]]

[[-50.90240358  17.63167724   7.7360209  ...   3.55657041  -5.82197358
   -1.72604005]
 [-52.84690919  19.14690749   7.27254551 ...   3.43259929  -5.63318106
   -2.0122316 ]
 [-54.61443917  19.92735811   8.10995831 ...   4.17520282  -5.38828678
   -2.75269933]
 ...
 [ 83.79819948  16.95241334  -8.25265611 ...   2.92390381  -4.59543822
   -2.99033503]
 [ 79.19578947  19.14436008  -6.93262976 ...   3.40475421  -3.66793327
   -3.57607629]
 [ 82.96885933  13.13513974  -9.07644299 ...   3.75100423  -4.79172198
   -3.03918865]]


In [108]:
prices_pca.head()

date          0          1         2         3         4         5  \
0  2013-09-23 -50.902404  17.631677  7.736021  2.596010  2.377569  4.244055   
1  2013-09-24 -52.846909  19.146907  7.272546  4.618575  0.102182  3.935519   
2  2013-09-25 -54.614439  19.927358  8.109958  4.920347 -0.421454  4.555335   
3  2013-09-26 -52.600566  19.941571  6.948113  4.806243  0.319779  5.065505   
4  2013-09-27 -52.370123  22.289064  8.410868  3.833372 -2.464882  4.359897   

           6         7         8         9  
0  12.883088  3.556570 -5.821974 -1.726040  
1  11.062930  3.432599 -5.633181 -2.012232  
2  10.119224  4.175203 -5.388287 -2.752699  
3   9.849605  3.266579 -5.974574 -1.922746  
4   7.988691  3.452709 -5.745204 -1.875131

In [109]:
djia_index = pd.read_csv('djia_index.csv')

In [97]:
djia_index.head()

date          ^DJI
0  2013-09-23  15401.379883
1  2013-09-24  15334.589844
2  2013-09-25  15273.259766
3  2013-09-26  15328.299805
4  2013-09-27  15258.240234

In [110]:
pearson_corr = np.corrcoef(prices_pca.iloc[:, 1], djia_index.iloc[:, 1])
pearson_corr

array([[1.        , 0.90965222],
       [0.90965222, 1.        ]])

In [111]:
with open('2.txt', 'w') as f:
    f.write(str(round(pearson_corr[0, 1], 2)))

In [100]:
abs(pca.components_[0])

array([1.61383840e-02, 1.20644923e-01, 5.16612711e-02, 5.04842369e-02,
       1.25859933e-01, 1.14089567e-01, 2.33906290e-01, 6.20513749e-03,
       2.51227032e-01, 2.88996029e-01, 2.64998795e-01, 9.31320168e-02,
       9.13948403e-02, 4.69879340e-02, 2.90549417e-02, 2.61068828e-02,
       3.29615584e-01, 7.13897133e-02, 7.62295699e-02, 2.11888868e-01,
       2.30922941e-02, 7.77316954e-02, 7.20594590e-03, 1.89479745e-01,
       3.21564017e-01, 5.36834873e-02, 5.79683946e-01, 1.09122230e-04,
       8.71614334e-02, 4.29421420e-02])

In [101]:
max_value_company_index = max(enumerate(abs(pca.components_[0])), key=lambda x: x[1])[0]

In [102]:
companies[max_value_company_index]

'V'

In [103]:
with open('3.txt', 'w') as f:
    f.write(companies[max_value_company_index])